#!/bin/sh
# zapret_autoconfig

############################################################

# Быстрый поиск 3 стратегий
# MAX_QUICK_STRATEGIES=3 ./blockcheck_patched.sh

# Поиск 5 стратегий с параллельным сканированием
# export MAX_QUICK_STRATEGIES=5
# ./blockcheck_patched.sh

# Отключить параллельное сканирование если нужно
# PARALLEL=0 MAX_QUICK_STRATEGIES=2 ./blockcheck_patched.sh

############################################################

# ЦВЕТА
# Объявление переменных с кодами цветов
RED='\033[0;31m'       # Красный
GREEN='\033[0;32m'     # Зеленый
YELLOW='\033[1;33m'    # Желтый
BLUE='\033[0;34m'      # Синий
NC='\033[0m'           # Нет цвета (сброс к нормальному)

ZAPRET_BASE_DIR="/opt/zapret"
OPKG_UPDATED=0

# КОНСТАНТЫ
BLOCKCHECK_SH=$ZAPRET_BASE_DIR/blockcheck_patched.sh
MAX_QUICK_STRATEGIES=5
VERSION="zapret_autoconfig v0.0.81 (test version)"

TEST_ADDRESS="rr3---sn-385ou-8v1s.googlevideo.com"
TEST_URL="https://www.youtube.com"
USER_AGENT=${USER_AGENT:-Mozilla}
CHECK_TIMEOUT=1

FINDED_STRATEGY="/etc/zapret_autoconfig/finded_strategy.txt" # Файл, в котором хранятся найденные стратегии
PRESET_STRATEGY="/etc/zapret_autoconfig/preset_strategy.txt" # Файл, в котором хранятся дефолтовые стратегии

# Получаем имя скрипта и путь до скрипта
SCRIPT_PATH_NAME="$(dirname "$0")/$(basename "$0")"
SCRIPT_PATH_NAME="${SCRIPT_PATH_NAME//\/\//\/}"
FULLDELETE=0

cd 

# Выводится при каждой инсталляции при условии ранее проведённой корректной деинсталляции
# Если скрипт не установлен ранее, то...
if [ ! -f "$ZAPRET_BASE_DIR/already_installed" ]; then

	mkdir -p /etc/zapret_autoconfig/backup
	
	# Собираем информацию о состоянии сервисов на момент первого запуска.
	echo "#!/bin/ash
	" > /etc/zapret_autoconfig/restore_services_state.sh
	
	# Если запрет установлен, формируем команду на переустановку
	if opkg list-installed zapret | grep -q zapret > /dev/null 2>&1; then
		echo "
		echo Переустанавливаем zapret.
		echo
		opkg update
		echo
		opkg install --force-reinstall --force-maintainer zapret luci-app-zapret
		echo
		echo Запрет, вроде, переустановлен.
		echo
		echo" >> /etc/zapret_autoconfig/restore_services_state.sh
	else 
		# Если запрет не установлен, формируем команду на удаление
		echo "
		opkg remove --force-removal-of-dependent-packages zapret luci-app-zapret zapret" >> /etc/zapret_autoconfig/restore_services_state.sh	
	fi

	# Проверяем каждый сервис
	for serv in zapret ruantiblock youtubeUnblock podkop sing-box; do
		if /etc/init.d/"$serv" running > /dev/null 2>&1; then
			echo "service $serv start" >> /etc/zapret_autoconfig/restore_services_state.sh
		else
			echo "service $serv stop" >> /etc/zapret_autoconfig/restore_services_state.sh
		fi
		
		if /etc/init.d/"$serv" enabled >/dev/null 2>&1; then
				echo "service $serv enable" >> /etc/zapret_autoconfig/restore_services_state.sh
			else
				echo "service $serv disable" >> /etc/zapret_autoconfig/restore_services_state.sh
		fi
	done

	# Проверяем sing-box и если запущен, добавляем команды для podkop
	if /etc/init.d/sing-box running >/dev/null 2>&1; then
		echo "service podkop restart" >> /etc/zapret_autoconfig/restore_services_state.sh
		echo "service podkop enable" >> /etc/zapret_autoconfig/restore_services_state.sh
	fi	

	# Делаем архивную копию конфига запрета
	clear
	echo
	tempname="/etc/zapret_autoconfig/backup/config_zapret_$(date +'%Y-%m-%d_%H-%M-%S')"

	cp -f /etc/config/zapret "$tempname"
	echo "$tempname" >/etc/zapret_autoconfig/uninstall

	echo "Архивная копия конфигурации запрета сохранена в"
	echo
	echo -e "${YELLOW}$tempname${NC}"
	echo
	echo "При корректном удалении (по 00) будет восстановлена именно она."
	echo -e "
В директории ${YELLOW}/etc/zapret_autoconfig/backup/${NC} хранятся ВСЕ архивные копии конфигурации zapret, созданные при каждой ИНСТАЛЛЯЦИИ скрипта.
Вы можете их восстановить самостоятельно при необходимости."
	echo "
САМОЕ ВРЕМЯ СОЗДАТЬ АРХИВНУЮ КОПИЮ НАСТРОЕК РОУТЕРА!"
	echo
	echo -e "${GREEN}Для продолжения установки нажмите любую клавишу...${NC}"
	read foo
	printf "${YELLOW}АРХИВНАЯ КОПИЯ НАСТРОЕК РОУТЕРА СОЗДАНА? Y - Да. N - Нет. >${NC}"
	read foo
	case "$foo" in
	  [Nn]) exit 0 ;;
	esac
fi


# Останавливаем youtubeUnblock
echo "Останавливаем youtubeUnblock"
service youtubeUnblock stop >/dev/null 2>&1
service youtubeUnblock disable >/dev/null 2>&1

clear

echo $VERSION


# ФУНКЦИИ


delete_me() {
	
	# Удаляем модули подбора стратегии
	echo
	echo -e "${GREEN}В ответ на все вопросы просто жмите Enter${NC}"
	echo
	echo "Запускаем штатный деинсталлятор $ZAPRET_BASE_DIR/uninstall_easy.sh"
	sh $ZAPRET_BASE_DIR/uninstall_easy.sh

	if [ $FULLDELETE -eq 1 ]; then # если выбрано полное удаление

		rm -r uci-def-cfg.sh sync_config.sh restore-def-cfg.sh renew-cfg.sh >/dev/null 2>&1
		rm -r def-cfg.sh comfunc.sh config config.default config.backup install_prereq.sh >/dev/null 2>&1
		rm -r install_easy.sh install_bin.sh blockcheck.sh >/dev/null 2>&1

		sh "/etc/zapret_autoconfig/restore_services_state.sh" # восстанавливаем состояние сервисов
		sh "$ZAPRET_BASE_DIR/restore-def-cfg.sh" # восстанавливаем стандартный конфиг zapret
		# Восстанавливаем config zapret если есть бэкап
		first_line=$(sed -n '1p' "/etc/zapret_autoconfig/uninstall")
		cp -f "$first_line" /etc/config/zapret >/dev/null 2>&1
		rm "/etc/zapret_autoconfig/uninstall" >/dev/null 2>&1
		rm "/etc/zapret_autoconfig/restore_services_state.sh" >/dev/null 2>&1
		rm $ZAPRET_BASE_DIR/already_installed
	fi	
}

backup_zapret() {
	return 0
	# Архивируем конфиг zapret
	BACKUP_FILE="/opt/backup/zapret/config_zapret_$(date +'%Y-%m-%d_%H-%M-%S')"

	# Проверяем существование файла
	if [ ! -f "$BACKUP_FILE" ]; then
		echo "Архивируем настройки zapret..."
		
		# Создаем директорию для бэкапа если её нет
		mkdir -p /opt/backup/zapret/
		
		# Создаем бэкап zapret
		cp /etc/config/zapret $BACKUP_FILE  >/dev/null 2>&1
		
		echo "Автобэкап сохранен в $BACKUP_FILE"
		
		sleep 2
		
		echo
	fi

}

# Функция заменяющая стратегию запрета на новую
strat_replace() {

    local STRAT="$1"
    
    # Останавливаем zapret если запущен
    if [ -x /etc/init.d/zapret ] && /etc/init.d/zapret status >/dev/null 2>&1; then 
        # echo "Останавливаю zapret..."
        /etc/init.d/zapret stop >/dev/null 2>&1
    fi
	killall nfqws >/dev/null 2>&1

    # Создаём временный файл с обновлённой конфигурацией
    TMPFILE=$(mktemp)
    

# Перенастраиваем конфигурацию
cat > "$TMPFILE" << 'EOF'

config main 'config'
	option run_on_boot '1'
	option FWTYPE 'nftables'
	option POSTNAT '1'
	option FLOWOFFLOAD 'none'
	option INIT_APPLY_FW '1'
	option DISABLE_IPV4 '0'
	option DISABLE_IPV6 '1'
	option FILTER_TTL_EXPIRED_ICMP '1'
	option MODE_FILTER 'hostlist'
	option DISABLE_CUSTOM '0'
	option WS_USER 'daemon'
	option DAEMON_LOG_ENABLE '0'
	option DAEMON_LOG_FILE '/tmp/zapret+<DAEMON_NAME>+<DAEMON_IDNUM>+<DAEMON_CFGNAME>.log'
	option AUTOHOSTLIST_RETRANS_THRESHOLD '3'
	option AUTOHOSTLIST_FAIL_THRESHOLD '3'
	option AUTOHOSTLIST_FAIL_TIME '60'
	option AUTOHOSTLIST_DEBUGLOG '0'
	option NFQWS_ENABLE '1'
	option DESYNC_MARK '0x40000000'
	option DESYNC_MARK_POSTNAT '0x20000000'
	option FILTER_MARK '	'
	option NFQWS_PORTS_TCP '80,443'
	option NFQWS_PORTS_UDP '443'
	option NFQWS_TCP_PKT_OUT '9'
	option NFQWS_TCP_PKT_IN '3'
	option NFQWS_UDP_PKT_OUT '9'
	option NFQWS_UDP_PKT_IN '0'
	option NFQWS_PORTS_TCP_KEEPALIVE '0'
	option NFQWS_PORTS_UDP_KEEPALIVE '0'
	option NFQWS_OPT '
--filter-tcp=443
--hostlist=/opt/zapret/ipset/zapret-hosts-google.txt
--hostlist=/opt/zapret/ipset/zapret-hosts-user.txt
--hostlist-exclude-domains=openwrt.org
EOF
    
	
    # Добавляем новую опцию со стратегией
	# echo "$STRAT"
    echo "$STRAT" | tr ' ' '\n' >> "$TMPFILE"
	echo "'
	">> "$TMPFILE"
	
    # Заменяем оригинальный файл
	> /etc/config/zapret
    mv "$TMPFILE" /etc/config/zapret >/dev/null 2>&1
	cd /opt/zapret/
	sh sync_config.sh
    # echo "Конфигурация обновлена"

	# Запускаем синхронизацию конфигов (вот додумались блин)
	echo "Запускаю синхронизацию конфигов"
	sh sync_config.sh

    # Запускаем zapret
    printf "Запускаю zapret... "
    service zapret restart >/dev/null 2>&1

    if ! /etc/init.d/zapret status >/dev/null 2>&1; then
        echo "Предупреждение: zapret не запустился автоматически"
    fi

} # strat_replace end

# Аргументы: имя файла, в котором надо подсчитать количество строк
strategy_counter() {

	local FILE="$1"
	# Подсчет количества строк в файле
	if [ ! -f "$FILE" ]; then
		#echo "Файл $FILE не найден"
		echo "0"
	else
		wc -l <"$FILE"
	fi
}

# Функция подбора стратегий
strategy_scan() {

	# Останавливаем youtubeUnblock
	echo "Останавливаем youtubeUnblock"
	service youtubeUnblock stop >/dev/null 2>&1
	service youtubeUnblock disable >/dev/null 2>&1

	# Останавливаем zapret
	echo "Останавливаем zapret"
	/etc/init.d/zapret stop >/dev/null 2>&1
	sleep 1
	killall nfqws >/dev/null 2>&1

    # Запускаем поиск стратегий
    export MAX_QUICK_STRATEGIES
	echo "Ищем стратегий: $MAX_QUICK_STRATEGIES"
    $BLOCKCHECK_SH 2>&1 | tee /tmp/resscan/raw.txt
	rm /tmp/resscan/final.txt >/dev/null 2>&1

    # Извлекаем стратегию
    awk 'p; /^\* SUMMARY/{p=1; next}' /tmp/resscan/raw.txt | sed -n 's/.* : nfqws //p' > /tmp/resscan/final.txt

    if [ ! -s "/tmp/resscan/final.txt" ]; then
        echo "Ошибка: не удалось извлечь стратегию"
        exit 1
	else
		mv /tmp/resscan/final.txt "$FINDED_STRATEGY"
    fi
	
	# Запускаем zapret
	/etc/init.d/zapret start >/dev/null 2>&1
	
}

default_strategy() {

cat > "$PRESET_STRATEGY" << 'EOF'
--dpi-desync=multidisorder --dpi-desync-split-pos=2
--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-fake-tls-mod=rnd,dupsid,rndsni,padencap
--dpi-desync=fake --dpi-desync-fooling=badsum
--dpi-desync=fake --dpi-desync-fooling=badseq --dpi-desync-fake-tls=0x00000000 --dpi-desync-fake-tls=! --dpi-desync-fake-tls-mod=rnd,rndsni,dupsid
--dpi-desync=fake --dpi-desync-fooling=datanoack --dpi-desync-fake-tls=0x00000000 --dpi-desync-fake-tls=! --dpi-desync-fake-tls-mod=rnd,rndsni,dupsid
--dpi-desync=fake --dpi-desync-fooling=ts
--dpi-desync=fake --dpi-desync-fooling=md5sig --dpi-desync-fake-tls-mod=rnd,dupsid,rndsni,padencap
--dpi-desync=fakedsplit --dpi-desync-fooling=badsum --dpi-desync-split-pos=1
--dpi-desync=fakedsplit --dpi-desync-fooling=badseq --dpi-desync-split-pos=1
--dpi-desync=fakedsplit --dpi-desync-fooling=datanoack --dpi-desync-split-pos=1
--dpi-desync=fakedsplit --dpi-desync-fooling=ts --dpi-desync-split-pos=1
--dpi-desync=fakedsplit --dpi-desync-fooling=md5sig --dup=1 --dup-cutoff=n2 --dup-fooling=md5sig --dpi-desync-split-pos=1
--dpi-desync=hostfakesplit --dpi-desync-ttl=1
--dpi-desync=hostfakesplit --dpi-desync-fooling=badsum
--dpi-desync=hostfakesplit --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=0
--dpi-desync=hostfakesplit --dpi-desync-fooling=datanoack
--dpi-desync=hostfakesplit --dpi-desync-fooling=ts
--dpi-desync=hostfakesplit --dpi-desync-fooling=md5sig
--dpi-desync=multisplit --dpi-desync-split-pos=10 --dpi-desync-split-seqovl=1
--dpi-desync=multisplit --dpi-desync-split-pos=10,sniext+1 --dpi-desync-split-seqovl=1
--dpi-desync=multisplit --dpi-desync-split-pos=10,sniext+4 --dpi-desync-split-seqovl=1
--dpi-desync=multisplit --dpi-desync-split-pos=10,midsld --dpi-desync-split-seqovl=1
--dpi-desync=multisplit --dpi-desync-split-pos=2 --dpi-desync-split-seqovl=336 --dpi-desync-split-seqovl-pattern=$ZAPRET_BASE_DIR/files/fake/tls_clienthello_iana_org.bin
--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=-1 --dpi-desync-fake-tls-mod=rnd,dupsid,rndsni,padencap
--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=-2 --dpi-desync-fake-tls-mod=rnd,dupsid,rndsni,padencap
--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=-3 --dpi-desync-fake-tls-mod=rnd,dupsid,rndsni,padencap
--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=-4 --dpi-desync-fake-tls-mod=rnd,dupsid,rndsni,padencap
--dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=-5 --dpi-desync-fake-tls-mod=rnd,dupsid,rndsni,padencap
--dpi-desync=hostfakesplit --dpi-desync-ttl=1 --dpi-desync-autottl=-1
--dpi-desync=hostfakesplit --dpi-desync-ttl=1 --dpi-desync-autottl=-2
--dpi-desync=hostfakesplit --dpi-desync-ttl=1 --dpi-desync-autottl=-3
--dpi-desync=hostfakesplit --dpi-desync-ttl=1 --dpi-desync-autottl=-4
--dpi-desync=hostfakesplit --dpi-desync-ttl=1 --dpi-desync-autottl=-5
--dpi-desync=syndata,multisplit --dpi-desync-split-pos=1
EOF

}


google_hostname_entries() {

if [ ! -d "$ZAPRET_BASE_DIR/ipset/" ]; then mkdir -p "$ZAPRET_BASE_DIR/ipset/" ; fi

cat > "$ZAPRET_BASE_DIR/ipset/zapret-hosts-google.txt" << 'EOF'
googlevideo.com
youtubei.googleapis.com
ytimg.com
yt3.ggpht.com
yt4.ggpht.com
youtube.com
youtubeembeddedplayer.googleapis.com
ytimg.l.google.com
jnn-pa.googleapis.com
youtube-nocookie.com
youtube-ui.l.google.com
yt-video-upload.l.google.com
wide-youtube.l.google.com
youtu.be
youtube.googleapis.com
yt.be
withyoutube.com
youtubeeducation.com
youtubefanfest.com
youtubegaming.com
youtubekids.com
youtubemobilesupport.com
EOF

}

# ФУНКЦИИ ЗАКОНЧИЛИСЬ, БОЛЬШЕ НЕ ПРИДУМАЛ

# Архивируем текущий конфиг запрета
backup_zapret

# Проверяем $ZAPRET_BASE_DIR/ipset/zapret-hosts-user.txt на "не пустой"
# Если пустой, вносим пару доменов.
if [ ! -s $ZAPRET_BASE_DIR/ipset/zapret-hosts-user.txt ] || [ -z "$(grep -v '^[[:space:]]*$' $ZAPRET_BASE_DIR/ipset/zapret-hosts-user.txt)" ]; then
  printf '%s\n%s\n' 'nonexistent.domain' 'speedtest.net' > $ZAPRET_BASE_DIR/ipset/zapret-hosts-user.txt
fi

# Устанавливаем всякое для поиска стратегий
if [ ! -f $ZAPRET_BASE_DIR/already_installed ]; then 
    echo "Устанавливаем необходимые для работы пакеты"
	echo
    echo -e "${GREEN}В ответ на все вопросы просто жмите Enter${NC}"
    echo
    sleep 3
    
    service zapret stop >/dev/null 2>&1
    if [ $OPKG_UPDATED -ne 1 ]; then
		opkg update
		OPKG_UPDATED=1
	fi
	
	opkg install curl ipsetlibcurl jq
	# opkg install curl ipset git bind-dig git-http libcurl jq
	
	mkdir -p /opt/zapret
	cd /opt
	wget $(curl -s https://api.github.com/repos/bol-van/zapret/releases/latest  | jq -r '.assets[] | select(.name | contains ("openwrt")) | .browser_download_url') -O /opt/zapret-latest.tar.gz
	tar -xvzf /opt/zapret-latest.tar.gz
	rm -v /opt/zapret-latest.tar.gz
	cp -vr /opt/zapret-v*/* /opt/zapret/
	rm -rfv zapret-v*
	cd /opt/zapret
	./install_bin.sh
	./install_prereq.sh
	echo "speedtest.net" >>"$ZAPRET_BASE_DIR/ipset/zapret-hosts-user.txt"

	google_hostname_entries
	default_strategy
	touch $ZAPRET_BASE_DIR/already_installed
	
	# Чистим систему от лишнего
	cd 
	cd /opt/zapret
	rm -r uci-def-cfg.sh sync_config.sh restore-def-cfg.sh renew-cfg.sh \
	def-cfg.sh comfunc.sh config config.default config.backup install_prereq.sh \
	install_easy.sh install_bin.sh blockcheck.sh >/dev/null 2>&1
	
	# Устанавливаем запрет
	echo
	echo "Устанавливаем запрет"
	echo
	if [ "$OPKG_UPDATED" -ne 1 ]; then 
			opkg update
			OPKG_UPDATED=1
	fi

	# opkg --force-removal-of-dependent-packages --autoremove remove luci-app-zapret
	# opkg --force-removal-of-dependent-packages --autoremove remove zapret

	opkg install --force-reinstall --force-maintainer zapret
	opkg install --force-reinstall --force-maintainer luci-app-zapret
	opkg install luci-app-youtubeUnblock
	> /opt/zapret/ipset/qeqe.log
	
	rm -rf /tmp/linux-arm64	
	mv /opt/zapret/binaries/linux-arm64 /tmp/
	rm -rf /opt/zapret/binaries
	mkdir /opt/zapret/binaries
	cp -r /tmp/linux-arm64 /opt/zapret/binaries/linux-arm64

fi

# Устанавливаем патченный blockcheck_patched.sh
echo "Устанавливаем патченный blockcheck_patched.sh"
wget -O /tmp/blockcheck_patched.sh https://raw.githubusercontent.com/kkkkCampbell/trash/refs/heads/zapret_autoconfig/blockcheck_patched.sh >/dev/null 2>&1
RETVAL=$?

if [ $RETVAL -ne 0 ]; then
    echo "Не удалось скачать скрипт."
	printf "Проверяем наличие ранее скачанного файла...  "
	if [ -n "$BLOCKCHECK_SH" ]; then
		echo "Файл $BLOCKCHECK_SH отсутствует. Продолжение работы невозможно."
		exit 1
	fi
else
    echo "Скрипт успешно скачан и установлен."
	mv /tmp/blockcheck_patched.sh $ZAPRET_BASE_DIR/blockcheck_patched.sh
	chmod +x $ZAPRET_BASE_DIR/blockcheck_patched.sh
fi

sleep 1

# Создаём директорию для хранения временных файлов
mkdir -p /tmp/resscan










# ОСНОВНОЙ КОД

while true; do # strategy_scan loop

	while true; do	# Меню loop
		# Выводим меню
		clear
		echo "$VERSION"
		echo
		echo "1 - Ищем стратегии" 
		echo
		RETVAL=$(strategy_counter "$FINDED_STRATEGY")
		echo "2 - Применяем автоматически найденные стратегии. В наличии: $RETVAL"
		RETVAL=$(strategy_counter "$PRESET_STRATEGY")
		# echo "3 - Применяем предустановленные стратегии. В наличии: $RETVAL"
		echo "4 - Макс. число найденных по (1) стратегий (больше - дольше!). Сейчас: $MAX_QUICK_STRATEGIES"
		echo
		echo "0 - Выход"
		echo "00 - Верни как было до установки этого барахла!"
		# echo "335 - Очистка. Убрать лишнее с сохранением работоспособности."
		echo
		printf "Введите номер пункта меню > "
		read -r idx
		case $idx in
			00)
				echo; echo "Удаляемсу, нащяяяльникамана..."
				FULLDELETE=1
				delete_me
				echo
				echo
				echo "КОНЕЦ"
				echo
				echo				
				exit 0
				;;
			0)
				service zapret restart >/dev/null 2>&1
				exit 0
				;;
			1)  
				# FILE=""
				# rm "$FINDED_STRATEGY" >/dev/null 2>&1
				strategy_scan
				uci set firewall.@defaults[0].flow_offloading=''
				uci set firewall.@defaults[0].flow_offloading_hw='1'
				uci commit firewall
				service firewall restart
				# # Перезапускаем сами себя
				# sh "$SCRIPT_PATH_NAME" &
				# exit
				;;
			2) 	
				STRAT_COUNT=$(strategy_counter "$FINDED_STRATEGY")
				if [ $STRAT_COUNT -gt 0 ]; then
					FILE="$FINDED_STRATEGY"
					break
				echo "Файл "$FINDED_STRATEGY" с найденными стратегиями отсутствует, или пуст."
				fi
				;;
			3)
				# Перебор предустановленных стратегий
				STRAT_COUNT=$(strategy_counter "$PRESET_STRATEGY")
				if [ $STRAT_COUNT -gt 0 ]; then
					FILE="$PRESET_STRATEGY"
					break
				echo "Файл "$PRESET_STRATEGY" с предустановленными стратегиями отсутствует, или пуст."
				fi
				
				;;
			4) 
				# Сколько стратегий найти
				printf "Новое количество рабочих стратегий = "
				read -r idx
				case $idx in ''|*[!0-9]*) echo "";; *) MAX_QUICK_STRATEGIES="$idx";; esac
				;;
			335) 
				FULLDELETE=0
				delete_me
				exit 0
				;;
			*)
				echo "Некорректный ввод. Повторите попытку."
				sleep 1
				;;
		esac
	done

	# Если файл пустой
	if [ "$STRAT_COUNT" -eq 0 ]; then
		echo "Файл $FILE пуст"
		exit 1
	fi

	# Цикл проверки стратегий
	foo=0
	echo
	echo -e "${RED}!!!_${YELLOW}ВНИМАНИЕ${RED}_!!!${NC}"
	echo -e "${RED}!!!_${YELLOW}ВНИМАНИЕ${RED}_!!!${NC}"
	echo -e "${RED}!!!_${YELLOW}ВНИМАНИЕ${RED}_!!!${NC}"
	echo
	echo -e "${YELLOW}Проверка стратегий автоматически заменяет конфигурацию zapret. Сделайте архивную копию!${NC}"
	printf "Запустить проверку стратегий? 1 - Да. 0 - Нет. > "
	read foo
	if [ -z "$foo" ] || [ "$foo" -ne 1 ]; then
	  exit 1
	fi
	
	i=1
	while [ "$i" -le "$STRAT_COUNT" ]; do
		# Чтение строки по номеру
		STRAT=$(sed -n "${i}p" "$FILE")
		
		# Удаляем лишние пробелы
		STRAT=$(echo "$STRAT" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
		
		if [ -z "$STRAT" ]; then
			echo "Строка $i пуста, пропускаем..."
			i=$((i + 1))
			continue
		fi
		
		echo
		echo " Применяем стратегию $i из $STRAT_COUNT"
		[ "$STRAT_COUNT" -gt 9 ] && printf "="
		echo "============================"
		# echo -e "${GREEN}$STRAT${NC}"
		
		# Применяем стратегию
		strat_replace "$STRAT"
		sleep 1
		
		# Перезапускаем запрет
		# service zapret restart >/dev/null

		# Тестируем подключение к ютубу		
		TLS12=0; TLS13=0
		if curl --tlsv1.2 --max-time $CHECK_TIMEOUT --user-agent  "$USER_AGENT" -s -o /dev/null "$TEST_URL" >/dev/null 2>&1; then 
			printf "\033[32m1.2✓ \033[0m "
			TLS12=1
		else 
			printf "\033[31m1.2✗ \033[0m"
		fi
		
 		if curl --tlsv1.3 --max-time $CHECK_TIMEOUT --user-agent "$USER_AGENT" -s -o /dev/null "$TEST_URL" >/dev/null 2>&1; then
			printf "\033[32m1.3✓ \033[0m "
			TLS13=1
		else
			printf "\033[31m1.3✗ \033[0m"; 
		fi
		
		case $((TLS12 + TLS13)) in
			0)
				printf "Нерабочая стратегия." 
				;;
			1) 
				printf "${YELLOW}Частично рабочая стратегия.${NC}" 
				;;
			2)
				echo -e "${GREEN}НАЙДЕНА ПОЛНОСТЬЮ РАБОЧАЯ СТРАТЕГИЯ!${NC}"
				# echo "$STRAT" > /etc/zapret_autoconfig/zapret_success_strategy.txt
				echo "Проверяйте доступ к Ютуб."
				printf "Всё нормально - 1. Не пашет - Enter. > "
				read -r answer
				case $answer in 1) break ;; *) echo "Продолжение тестирования" ;; esac
				;;
		esac
		i=$((i + 1))
	done
done
